# Generated by Django 4.2.1 on 2023-12-01 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
    ]
