# Generated by Django 4.2.1 on 2023-12-02 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_delete_author_remove_post_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostHashTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hashtag", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="comment",
            name="content",
        ),
        migrations.AddField(
            model_name="comment",
            name="comment",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.CreateModel(
            name="Share_post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=200)),
                ("date_time", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="blog.post"
                    ),
                ),
            ],
        ),
    ]
