# Generated by Django 4.2.1 on 2023-12-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_posthashtag_remove_comment_content_comment_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hashtags",
            field=models.ManyToManyField(
                blank=True, related_name="blog_posts", to="blog.posthashtag"
            ),
        ),
    ]
